package br.com.zup.edu.nossozenity.zupper;

public enum TipoKudo {
    AGRADECIMENTO,LIDERANCA_INSPIRADORA,EXCELENTE_TRABALHO,EXCELENTE_MENTOR, OTIMA_APRESENTACAO, ALEM_DAS_EXPECTATIVAS,
    TRABALHO_EM_EQUIPE, TORNA_O_TRABALHO_DIVERTIDO, IDEIAS_ORIGINAIS;
}
